:server:
  :base_ip: 10.10.10.0
  :bridgednets: # real networks to bridge via the VPN server
    - 172.16.0.0
  :subnets: # subnets that exist only on the VPN
    - 10.10.11.0
  :user: nobody
  :group: nogroup
  :root: /root/openvpn
  :log: /var/log/openvpn.log
  :host: vpn.foocorp.com
  :port: 1194

:client:
  :subnet: 172.16.0.0
  :local_endpoint: 10.10.10.100
  :remote_endpoint: 10.10.10.1

:key_properties:
  :country: US
  :province: CA
  :city: San Francisco
  :organization: FooCorp Inc
  :email: sec@foocorp.com
